### ISSUE TITLE
Default Eviction policy

### ISSUE THREAD

**Issue by taooceros** [neon-sunset/fast-cache#107]
I wonder what's the default eviction policy? With a relatively small cache size (150), it seems like we are experiencing consistent eviction of the recently inserted item🤔.

**Comment by neon-sunset** [comment]
Items are evicted when either quick list or full eviction runs - either removes expired items from the cache.

In addition, when you specify a desired total cache item limit, upon trying to add a new item, it will trim the existing items to make space. This will trim at least 5% of the cache, no less than 1 item and no more than 512 to ensure that the write is executed within reasonable latency.

https://github.com/neon-sunset/fast-cache/blob/main/src/FastCache.Cached/CacheManager.cs#L132-L164

**Comment by taooceros** [comment]
Thanks for the wonderful reply. I am sorry for the late response as I miss this message. I will double check about the code I wrote.

**Comment by taooceros** [comment]
On the other hand, I agree with you that it is a totally overkill to use `FastCache` and I think we should migrate to a library which can support a more complex eviction policy (like lfu).

I think the eviction policy of `FastCache` depends on the enumerator. However, that seems to consistently evict most recently inserted item (maybe because our limit is small). I do feel like cache hit rate is an important metric a good cache library beyond speed.
