### ISSUE TITLE
CleanCache

### ISSUE THREAD

**Issue by troepolik** [neon-sunset/fast-cache#44]
Is it possible to clean cache?
I didn't find method like `Cached<T>.Clear()`

**Comment by troepolik** [comment]
O, I guess it is `CacheManager.Trim<TKey, TValue>(100);`

**Comment by troepolik** [comment]
"with the assumption that you want to remove not yet expired items added by benchmark fixture."
No, I want remove just all of them.
like `CacheManager.QueueFullClear<string, SessionToken>();`
but without queue like `CacheManager.Clear<string, SessionToken>();` would be  great
now I have workaround for benchmark:
on start:
`Environment.SetEnvironmentVariable("FASTCACHE_INLINE_TRIM_COUNT_THRESHOLD", uint.MaxValue.ToString());`
and clear by: `CacheManager.Trim<TKey, TValue>(100);`
))

**Comment by neon-sunset** [comment]
If it works for you, it's just an opinionated library that focuses on perf + being terse to use :D

**Comment by neon-sunset** [comment]
I'm going to close this issue as answered. Let me know if you have any questions.

**Comment by troepolik** [comment]
Any way, I've created pr for give us ability to call awaitable Full clean. To be sure it was cleared. 
Could you be so kind to approve it or give me feedback what can I fix in it to merge?
