### ISSUE TITLE
Delete cache item

### ISSUE THREAD

**Issue by closte** [neon-sunset/fast-cache#64]
How do you delete the cached item once the SalesReport need to be updated

```
public SalesReport GetReport(Guid companyId)
{
  if (Cached<SalesReport>.TryGet(companyId, out var cached))
  {
    return cached;
  }

  var report = // Expensive operation: retrieve and compute data

  return cached.Save(report, TimeSpan.FromMinutes(60));
}
```

`Cached<SalesReport>` only contains `TryGet` and `Save` but not `Delete`.

**Comment by closte** [comment]
> Hi @closte,
> 
> You do not need to delete expired cache items manually because `FastCache` does so automatically. If your cache item has expired and you want to save a new updated value, you just need to call `cached.Save(...)` once again. If you want to remove the cache item regardless of its current status, you can call `cached.Remove()`.

In that case, I must first read the cached item to be able to delete it. How do I remove multiple cache items in the GetReports function on the following example:

```
    public List<string> GetReports(int companyId = 5, bool clearCache)
  {

      if (clearCache == true)
      {

          var deleteCacheItems = new List<string>() { "report1_" + companyId, "report2_" + companyId };

          //delete GetReport1 cache for companyId = 5  ; CacheKey<string> = report1_5
          //delete GetReport2 cache for companyId = 5  ; CacheKey<string> = report2_5
      }

      var report = new List<string> { GetReport1(companyId), GetReport2(companyId) };

      return report;
  }


  public string GetReport1(int companyId)
  {
      if (Cached<string>.TryGet("report1_"+companyId, out var cached))
      {
          return cached;
      }

      var report = // Expensive operation: retrieve and compute data

      return cached.Save(report, TimeSpan.FromMinutes(60));
  }

  public string GetReport2(int companyId)
  {
      if (Cached<string>.TryGet("report2_" + companyId, out var cached))
      {
          return cached;
      }

      var report = // Expensive operation: retrieve and compute data

      return cached.Save(report, TimeSpan.FromMinutes(60));
  }

```

**Comment by tcsaddul** [comment]
Remove the cached item where there is a change in the underlying data.  Look for codes where you change or update the "Sales" data.

**Comment by neon-sunset** [comment]
> How do I remove multiple cache items in the GetReports function

```cs
using FastCache.Collections;

var reportKeys = ...; // some sequence which contains reportKey1, reportKey2, etc.;
CachedRange<SalesReport>.Remove(reportKeys);
```

By the way, you don't need to concatenate cache item keys, you can use multi-argument method overloads:
```cs
Cached<SalesReport>.TryGet(reportKey, companyId, out var cached)
```

If you do, then for `CachedRange` such multi-value keys will be represented as `(reportKey, companyId)` e.g.
```cs
var companyId = 1234;
var reportKeys = ...;

CachedRange<SalesReport>.Remove(reportKeys.Select(k => (k, companyId)));
```

**Comment by closte** [comment]
> > How do I remove multiple cache items in the GetReports function
> 
> ```cs
> using FastCache.Collections;
> 
> var reportKeys = ...; // some sequence which contains reportKey1, reportKey2, etc.;
> CachedRange<SalesReport>.Remove(reportKeys);
> ```
> 
> By the way, you don't need to concatenate cache item keys, you can use multi-value key method overloads:
> 
> ```cs
> Cached<SalesReport>.TryGet(reportKey, companyId, out var cached)
> ```
> 
> If you do, then for `CachedRange` such multi-value keys will be represented as `(reportKey, companyId)` e.g.
> 
> ```cs
> var companyId = 1234;
> var reportKeys = ...;
> 
> CachedRange<SalesReport>.Remove(reportKeys.Select(k => (k, companyId)));
> ```

Didnt tested but looks like this is what I was looking for. You can try to update the documentation because I came up with this question just after 5 minutes of testing.

Thanks!
